package main

import (
	"fmt"

	"github.com/joho/godotenv"
)

const geminiAPIURL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"

func main() {
	err := godotenv.Load()
	if err != nil {
		fmt.Printf("error loading .env file: %v\n", err)
	}

	branch, err := getCurrentBranch()
	if err != nil {
		fmt.Println("Error fetching current branch:", err)
		return
	}

	commits, err := getCommits(branch)
	if err != nil {
		fmt.Println("Error fetching commits:", err)
		return
	}

	fmt.Println("Document generated by AI:", sendMessageAI(commits))
}
