package main

import (
	"fmt"
	"os"

	autodocument "github.com/yusufguntav/Auto-Document"
)

func main() {
	doc, err := autodocument.GenerateDocumentation()
	if err != nil {
		fmt.Printf("Error generating documentation: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Document generated by AI:")
	fmt.Println(doc)
}
